import { render } from "react-dom";
import React, { Suspense, useEffect, useRef, useMemo } from "react";
import { Canvas, useThree, useFrame, extend } from "@react-three/fiber";
import { useGLTF, Stage, Stars } from "@react-three/drei";
import "./index.css";

// Component auto-generated by GLTFJSX: https://github.com/react-spring/gltfjsx
function Spaceship(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/StarSparrow03.glb");

  useFrame(() => (group.current.rotation.y += 0.004));

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.StarSparrow03.geometry}
        material={materials.StarSparrowBlue}
        position={[0, 0, 0]}
      />
    </group>
  );
}

function App() {
  return (
    <Canvas
      shadows
      dpr={[1, 2]}
      camera={{ position: [0, 0, 12], fov: 35 }}
      gl={{ antialias: false }}
    >
      <color attach="background" args={["#050505"]} />
      <Suspense fallback={null}>
        <Stage intensity={1.5}>          
          <Spaceship></Spaceship>
        </Stage>
        <Stars />
      </Suspense>
    </Canvas>
  );
}

render(<App />, document.querySelector("#root"));
